### ISSUE TITLE
Index error in patchwarp_affine `warp_success` variable call

### ISSUE THREAD

**Issue by bahanonu** [ryhattori/PatchWarp#2]
Hi, thanks again for putting up the code for PatchWarp. Using most recent PatchWarp main branch on Matlab 2020a. PatchWarp encounters an error within `patchwarp_affine` when attempting to call variable `warp_success` with certain movies.

It appears this is because `warp_success` is defined as a scalar/binary output in `ecc_patchwarp`, see

https://github.com/ryhattori/PatchWarp/blob/c6203f45114fdf32dd335d885e1e2dd2bbbc6892/PatchWarp/utils/ecc_patchwarp/ecc_patchwarp.m#L420-L428

And yet in `patchwarp_affine` it is called with `(warp_success(i1,i2,i3) == 0)`, or as a 3D matrix leading to index issues. This error usually is not encountered as the short-circuit `||` leads to that expression not being called since it is second.

https://github.com/ryhattori/PatchWarp/blob/c6203f45114fdf32dd335d885e1e2dd2bbbc6892/PatchWarp/patchwarp_affine.m#L177

This could potentially be fixed if `warp_success` in the below line is changed to `warp_success(i1,i2,i3)`.
https://github.com/ryhattori/PatchWarp/blob/c6203f45114fdf32dd335d885e1e2dd2bbbc6892/PatchWarp/patchwarp_affine.m#L165

**Comment by ryhattori** [comment]
Thanks for reporting this issue. This was due to missing indices in line 165. I fixed this issue and updated patchwarp_affine.m.
