### ISSUE TITLE
Java.io.File does not work when paths are specified using character vectors

### ISSUE THREAD

**Issue by ehennestad** [ryhattori/PatchWarp#3]
Hi, 
I am excited to try out this new motion correction algorithm. Just wanted to report a small issue, namely that java.io.File fails if paths are specified as character vectors and not strings. I got this error from the fastdir function:

```
No constructor 'java.io.File' with matching signature found.

Error in fastdir (line 11)
    jif = java.io.File(dir_name);
```

**Comment by ryhattori** [comment]
It seems to work with character vectors on my PC. Which version of MATLAB are you using? Also, what is your OS?

**Comment by ehennestad** [comment]
MATLAB Version: 9.9.0.1592791 (R2020b) Update 5
Operating System: macOS  Version: 11.6 Build: 20G165 
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

**Comment by ryhattori** [comment]
I tried Matlab 2020b on Windows with Java 1.8.0 or Matlab 2019b on macOS version 10.15.3. fastdir worked for both character vectors and strings in both cases. Just to clarify, do you mean you get the error with java.io.File('/.../.../.../...') but do not get the error with java.io.File("/.../.../.../...")?

**Comment by ehennestad** [comment]
Oh, sorry, this is my bad! Turns out what I had tried was to supply a cell array of character vector in the ops, and then I didn't realise the char was in a cell array before trying again with a string upon when it worked.
