### ISSUE TITLE
Error when attempting warp correction

### ISSUE THREAD

**Issue by kirolle** [ryhattori/PatchWarp#5]
Running the rigid motion correction works fine. I'm using the demo file as a template. After finishing this part and starting the warp correction, I receive the following warnings and errors: 

> Loading downsampled_perstack file...

> Warning: Total frames are not a multiple of n_ch. 

>  In read_tiff (line 62)

> In patchwarp_affine (line 55)

> In patchwarp (line 150)

> In patchwarp_demo (line 123) 

> Estimating affine transformation matrices...

> n_split4warpinit is too large
> n_split4warpinit was changed to 4
> Applying affine transformations...
> Error using patchwarp_affine
> warp number does not match file number

> Error in patchwarp (line 150)
>     patchwarp_affine(save_path_prewarp, save_path_postwarp, ops.n_ch, ops.align_ch, ops.affine_norm_radius, ops.warp_template_tiffstack_num, ops.warp_movave_tiffstack_num, ops.warp_blocksize, ops.warp_overlap_pix_frac, ops.n_split4warpinit, ops.edge_remove_pix, ops.affinematrix_abssum_threshold, ops.affinematrix_abssum_jump_threshold, ops.affinematrix_rho_threshold, ops.affinematrix_medfilt_tiffstack_num, ops.transform, ops.warp_pyramid_levels, ops.warp_pyramid_iterations, ops.downsample_frame_num, ops.worker_num, ops.network_temp_copy);
> 
> Error in patchwarp_demo (line 123)
> patchwarp(ops);

 
I would appreciate an idea of the issue and a potential solution.

**Comment by ryhattori** [comment]
Could you copy-paste your ops parameter set you specified as the input? Also, let me know what kind of image files you are using (how many tif files, how many frames per tif file).

**Comment by ryhattori** [comment]
Sorry, I just noticed that you used the demo files. Do you mean you downloaded these files "https://doi.org/10.6084/m9.figshare.19212501.v1" and just ran patchwarp_demo.m after specifying "patchwarp_path", 'ops.source_path', and 'ops.save_path'?

**Comment by kirolle** [comment]
Yes, exactly, I tried to play around with the settings in an attempt to fix it, but I couldn't resolve it yet.

**Comment by ryhattori** [comment]
Did you make sure that you did not change any other parameters in patchwarp_demo.m exept for "patchwarp_path", 'ops.source_path', and 'ops.save_path'? Which version of MATLAB are you using?

**Comment by kirolle** [comment]
I changed the "patchwarp_path" to the path where the toolbox is located in my system. The same goes for ops.source pointing towards the files I wanted to use the script on and ops.save pointing towards the path I would like to store them.
I changed ops.n_ch to 2 since we used two channels in our data.  
 I tried it on the 2023b preview and am now downloading the 2023a build to test it.

**Comment by ryhattori** [comment]
I see. I have not tested the code on two-channel data for a while after updating many things. Perhaps some previous updates made the warp correction imcompatible with 2-channel data. I need to look into it.

**Comment by kirolle** [comment]
I appreciate your help. I will also try to resolve the issue tomorrow. I will let you know if I find a solution or narrow it down a bit more.

**Comment by ryhattori** [comment]
I just had to edit line 55 of "patchwarp_affine.m" I uploaded the new "patchwarp_affine (line 55)" which should work with ops.n_ch = 2

**Comment by kirolle** [comment]
Thank you a lot! 
It works like a charm now.
