### ISSUE TITLE
Setting ops.n_ch = 2 quarters the amount of saved images.

### ISSUE THREAD

**Issue by kirolle** [ryhattori/PatchWarp#6]
First, thank you again for this great toolbox and the last fix for two-channel data.
Working with your toolbox, I found another potential bug. When using two-channel data and setting ops.n_ch = 2, ops.run_rigid_mc = 1, and ops.run_affine_wc = 1, when calling patchwarp(ops), the resulting images contain only a quarter of the original.
The expected behavior would be half of the images. 
The issue is related to the parameter n_ch being passed to both correction functions. 
My quick and dirty fix is to hardcode ops.n_ch = 1 in the patchwarp_affine.m file. This should make the most sense for most applications.
Sincerely 
- Kilian Rolle

**Comment by ryhattori** [comment]
Thank you for reporting this bug! I fixed this bug in the patchwarp_affine.m by inserting n_ch = 1 and align_ch = 1.
